"""
model_registry.py — shared save/load helpers for PharmaSync's trained
ML models.

Why this exists: before this, every model (RandomForest per medicine,
Holt-Winters/LinearRegression, KMeans, Isolation Forest, the chatbot's
intent classifier) retrained from scratch on every single script run /
every Django process start. That meant there was never one canonical
"the model currently in production" to point to, no record of when a
model was last trained or on how much data, and every prediction paid
the cost of a fresh .fit() even when nothing had changed.

This module gives every model in the project one consistent way to:
  1. save itself to disk, with metadata (when trained, on how many
     rows/examples, any extra context worth recording)
  2. check whether a saved version exists and is still "fresh enough"
     to reuse, vs. stale enough to warrant retraining
  3. load the saved version instead of retraining

Nothing here changes *what* gets predicted or the model/feature logic
of any script — it only changes whether a fresh .fit() happens on every
call, or a saved model is reused between scheduled retrains. Trained
models are written to python-service/models/, one <name>.pkl (the
model object, via joblib) + one <name>.meta.json (metadata) per model.
That folder is safe to .gitignore — it's regenerated by running the
training path once.
"""

import os
import json
from datetime import datetime, timezone

import joblib

MODELS_DIR = os.path.join(os.path.dirname(__file__), '..', 'models')
os.makedirs(MODELS_DIR, exist_ok=True)


def _paths(name, version=None):
    if version:
        return (
            os.path.join(MODELS_DIR, f'{name}_{version}.pkl'),
            os.path.join(MODELS_DIR, f'{name}.meta.json'),
        )
    return (
        os.path.join(MODELS_DIR, f'{name}.pkl'),
        os.path.join(MODELS_DIR, f'{name}.meta.json'),
    )


def save_model(name, model, metadata=None):
    """
    Persist a fitted model + metadata under MODELS_DIR/<name>.*

    Saves both a canonical `<name>.pkl` file for seamless active serving and a
    versioned `<name>_<version>.pkl` artifact (e.g. demand_forecast_rf_models_20260801_204419.pkl)
    with version & timestamp tracking in metadata.
    """
    now = datetime.now(timezone.utc)
    version = now.strftime("%Y%m%d_%H%M%S")
    version_tag = f"v_{version}"
    
    canonical_model_path, meta_path = _paths(name)
    versioned_model_path, _ = _paths(name, version=version)

    # Save both canonical pointer and timestamped versioned artifact
    joblib.dump(model, canonical_model_path)
    joblib.dump(model, versioned_model_path)

    meta = {
        'name': name,
        'version': version_tag,
        'trained_at': now.isoformat(),
        'artifact_file': os.path.basename(versioned_model_path),
        'canonical_file': os.path.basename(canonical_model_path),
        **(metadata or {}),
    }
    with open(meta_path, 'w') as f:
        json.dump(meta, f, indent=2, default=str)
    return meta


def load_model(name):
    """Returns (model, metadata), or (None, None) if nothing saved yet
    for this name — that's the normal "never trained before" state, not
    an error, so callers should treat it as "go ahead and train"."""
    canonical_model_path, meta_path = _paths(name)
    if not os.path.exists(meta_path):
        return None, None
    
    with open(meta_path) as f:
        meta = json.load(f)

    # Try versioned artifact first, falling back to canonical file
    artifact_file = meta.get('artifact_file')
    model_path = os.path.join(MODELS_DIR, artifact_file) if artifact_file else canonical_model_path
    if not os.path.exists(model_path):
        model_path = canonical_model_path

    if not os.path.exists(model_path):
        return None, None

    model = joblib.load(model_path)
    return model, meta


def get_model_info(name):
    """Returns metadata dict for the model, or None if not saved yet."""
    _, meta = load_model(name)
    return meta


def is_stale(metadata, max_age_hours):
    """
    True if there's no metadata yet (nothing trained/saved), or the
    saved model is older than max_age_hours — i.e. it's time to retrain
    rather than keep serving the saved one. Each caller picks its own
    max_age_hours based on how often its underlying data actually
    changes meaningfully (see the MAX_MODEL_AGE_HOURS constant defined
    near the top of each script that uses this).
    """
    if not metadata or 'trained_at' not in metadata:
        return True
    trained_at = datetime.fromisoformat(metadata['trained_at'])
    if trained_at.tzinfo is None:
        trained_at = trained_at.replace(tzinfo=timezone.utc)
    age_hours = (datetime.now(timezone.utc) - trained_at).total_seconds() / 3600
    return age_hours >= max_age_hours

